apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cu-connex
  region: ap-southeast-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 4
    maxSize: 10
    availabilityZones: ["ap-southeast-1a" , "ap-southeast-1b" , "ap-southeast-1c"]
    iam:
      withAddonPolicies:
        autoScaler: true
    ssh:
      publicKeyName: cu-connex