apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/event-depl.yaml
      - ./infra/k8s/expiration-depl.yaml
      - ./infra/k8s/users-depl.yaml
      - ./infra/k8s-dev/ingress.yaml
build:
  local:
    push: false
  artifacts:
    - image: palsp/connex-users
      context: users
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: palsp/connex-auth
    #   context: auth
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    - image: palsp/connex-event
      context: event-services
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.go'
            dest: .
    - image: palsp/connex-expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: palsp/connex-web
    #   context: web
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: '**/*.ts'
    #         dest: . 
