/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

import { CompilerContext } from "@bit/bit.envs.common.compiler-types";
export { CompilerContext };
import { GenericObject } from "@bit/bit.envs.common.compiler-types";
export { GenericObject };
