apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mysql
  template:
    metadata:
      labels:
        app: auth-mysql
    spec:
      containers:
        - name: auth-mysql
          image: mysql
          args:
            - "--default-authentication-plugin=mysql_native_password"
          env:
            # this should be change to secret in production
            - name: MYSQL_ROOT_PASSWORD
              value : password
            - name: MYSQL_DATABASE
              value : auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mysql-srv
spec:
  selector:
    app: auth-mysql
  ports:
    - name: db
      port: 3306
      targetPort: 3306
