apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
        - name: event
          image: palsp/connex-event
          env:
            - name: DB_HOST
              value: 'event-mysql-srv'
            - name: DB_USER
              value: 'root'
            - name : DB_NAME
              value: 'event_db'
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-db-secret
                  key: DB_PASSWORD
            - name : JWT_KEY
              valueFrom:
                secretKeyRef:
                  name : jwt-secret
                  key: JWT_KEY
      initContainers:
        - name: init-wait
          image: alpine
          command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 event-mysql-srv 3306 && exit 0 || sleep 3; done; exit 1"]
---
apiVersion: v1
kind: Service
metadata:
  name: event-srv
spec:
  selector:
    app: event
  ports:
    - name: event
      protocol: TCP
      port: 3000
      targetPort: 3000
