apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      labels:
        app: event
    spec:
      containers:
        - name: event
          image: palsp/connex-event
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: event-db-host
                  key: DB_HOST
            - name: DB_USER
              value: 'root'
            - name : DB_NAME
              value: 'event_db'
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: event-db-secret
                  key: DB_PASSWORD
            - name : JWT_KEY
              valueFrom:
                secretKeyRef:
                  name : jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name:  NATS_CLUSTER_ID
              value: 'connex'
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-access-key
                  key: AWS_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws_region
                  key: AWS_REGION
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-key
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: aws-bucket
                  key: AWS_BUCKET

      # initContainers:
      #   - name: init-wait
      #     image: alpine
      #     command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 event-mysql-srv 3306 && exit 0 || sleep 3; done; exit 1"]
---
apiVersion: v1
kind: Service
metadata:
  name: event-srv
spec:
  selector:
    app: event
  ports:
    - name: event
      protocol: TCP
      port: 3000
      targetPort: 3000
