apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
        - name: recommendation
          image: palsp/connex-recommendation
          env:
          # add env var here 
            - name: DB_HOST
              value: "users-mysql-srv"
            - name: DB_USER
              value: "root"
            - name: DB_SCHEMA
              value: "user_db"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: DB_PASSWORD
      initContainers:
        - name: init-wait
          image: alpine
          command:
            [
              "sh",
              "-c",
              "for i in $(seq 1 300); do nc -zvw1 users-mysql-srv 3306 && exit 0 || sleep 3; done; exit 1",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-srv
spec:
  selector:
    app: recommendation
  ports:
    - name: recommendation
      protocol: TCP
      port: 3000
      targetPort: 3000
