apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-srv
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: {{ .Values.app.name}}
      protocol: {{ .Values.app.service.protocol }}
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.container.port }}
