import { UsersData } from "@src/mockData/Models/index";

const mockFriendLists: UsersData[] | [] = [
  {
    id: "1",
    name: "NAT",
    interests: {
      Technology: [],
      Business: ["Marketing", "StartUp"],
      Design: [],
    },
    // interest: "Marketing, Startup",
    faculty: "Engineering",
    year: "3",
    role: "Developer",
    bio: "",
    image: "",
  },
  {
    id: "2",
    name: "Loong",
    interests: {
      Technology: [],
      Business: ["Marketing", "StartUp"],
      Design: [],
    },
    // interest: "AI, ",
    faculty: "Engineering",
    year: "3",
    role: "Developer",
    bio: "",
    image: "",
  },
  {
    id: "3",
    name: "Matoom",
    interests: {
      Technology: [],
      Business: ["Marketing", "StartUp"],
      Design: [],
    },
    // interest: "Sugi",
    faculty: "Engineering",
    year: "3",
    role: "Developer",
    bio: "",
    image: "",
  },
  {
    id: "4",
    name: "Home",
    interests: {
      Technology: [],
      Business: ["Marketing", "StartUp"],
      Design: [],
    },
    // interest: "Defi",
    faculty: "Engineering",
    year: "3",
    role: "Developer",
    bio: "",
    image: "",
  },
  {
    id: "5",
    name: "Pal",
    interests: {
      Technology: [],
      Business: ["Marketing", "StartUp"],
      Design: [],
    },
    // interest: "PS5",
    faculty: "Engineering",
    year: "3",
    role: "Developer",
    bio: "",
    image: "",
  },
  {
    id: "6",
    name: "Bird",
    interests: {
      Technology: [],
      Business: ["Marketing", "StartUp"],
      Design: [],
    },
    // interest: "Girls",
    faculty: "Engineering",
    year: "3",
    role: "Developer",
    bio: "",
    image: "",
  },
  {
    id: "7",
    name: "Bank",
    interests: {
      Technology: [],
      Business: ["Marketing", "StartUp"],
      Design: [],
    },
    // interest: "Sleep",
    faculty: "Engineering",
    year: "3",
    role: "Developer",
    bio: "",
    image: "",
  },
  {
    id: "8",
    name: "Saint",
    interests: {
      Technology: [],
      Business: ["Marketing", "StartUp"],
      Design: [],
    },
    // interest: "City",
    faculty: "Engineering",
    year: "3",
    role: "Developer",
    bio: "",
    image: "",
  },
  {
    id: "9",
    name: "Anon",
    interests: {
      Technology: [],
      Business: ["Marketing", "StartUp"],
      Design: [],
    },
    // interest: "Developer",
    faculty: "Engineering",
    year: "3",
    role: "Developer",
    bio: "",
    image: "",
  },
  {
    id: "10",
    name: "Mon",
    interests: {
      Technology: [],
      Business: ["Marketing", "StartUp"],
      Design: [],
    },
    // interest: "PM",
    faculty: "Engineering",
    year: "3",
    role: "Developer",
    bio: "",
    image: "",
  },
];

export default mockFriendLists;
