apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}-mysql-srv
spec:
  selector:
    app: {{ .Values.mysql.name }}-mysql
  ports:
    - name: {{ .Values.mysql.group }}
      port: {{ .Values.mysql.container.port }}
      targetPort: {{ .Values.mysql.service.port }}
