name: deploy-auth

on:
  push:
    branches: 
      - develop
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image 
        run: cd auth && npm run build && docker build -t palsp/connex-auth . 
      - name: Login to Docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Image to Docker Hub
        run: docker push palsp/connex-auth
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Use k8s context
        run: doctl kubernetes cluster kubeconfig save cu-connex
      - name: Restart deployment
        run: kubectl rollout restart deployment auth-depl
