name: test-event

on:
  pull_request:
    paths:
      - 'event-services/**'
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name : Shutdown Ubuntu MySQL(SUDO)
        run : sudo service mysql stop
      - name : Set up MySQL 
        uses: mirromutth/mysql-action@master
        with:
          mysql root password : ${{secrets.DB_TEST_PASSWORD}}
      - name : npm install and test
        run: cd event-services && go get -d -v ./... && go test ./...


    
