name: test-auth

on:
  pull_request:
    paths:
      - 'auth/**'
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name : Shutdown Ubuntu MySQL(SUDO)
        run : sudo service mysql stop
      - name : Set up MySQL 
        uses: mirromutth/mysql-action@master
        with:
          mysql root password : ${{secrets.DB_TEST_PASSWORD}}
      - name : npm install and test
        run: cd auth && npm install && npm run test:ci --password=${{secrets.DB_TEST_PASSWORD}}


    
